[neovim]
src = "~/.config/nvim/"
dest = "nvim"

[zsh]
src = "~/.zshrc"
dest = "zshrc"

[tmux]
src = "~/.tmux.conf"
dest = "tmux.conf"

[lem]
src = "~/.lem/init.lisp"
dest = "lem-init.lisp"

[emacs]
src = "~/.emacs.d/init.el"
dest = "emacs-init.el"

[proxy]
src = "~/proxy.sh"
dest = "proxy.sh"

[kitty_terminal]
src = "~/.config/kitty/"
dest = "kitty"

[sway]
src = "~/.config/sway/config"
dest = "sway-config"
